# Generated by Django 4.0.5 on 2023-01-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
